services:
  bot-db:
    image: mysql:5.7
    #platform: linux/amd64
    container_name: bot-db
    environment:
      MYSQL_ROOT_PASSWORD: bot
      MYSQL_DATABASE: bot
      MYSQL_USER: bot
      MYSQL_PASSWORD: bot
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
